"""initial2

Revision ID: 9065968346fa
Revises: 0f210bb8742d
Create Date: 2024-01-13 19:42:43.100838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9065968346fa'
down_revision: Union[str, None] = '0f210bb8742d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_features', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_features', type_='foreignkey')
    # ### end Alembic commands ###
